# Order Statuses
STATUS_PENDING = "Pending"
STATUS_IN_PROGRESS = "In Progress"
STATUS_COMPLETED = "Completed"
STATUS_DELIVERED = "Delivered"
STATUS_CANCELLED = "Cancelled"

ORDER_STATUSES = [
    STATUS_PENDING,
    STATUS_IN_PROGRESS,
    STATUS_COMPLETED,
    STATUS_DELIVERED,
    STATUS_CANCELLED,
]

# Service Types
SERVICE_WASH_DRY_FOLD = "Wash, Dry, Fold"
SERVICE_DRY_CLEANING = "Dry Cleaning"
SERVICE_IRONING = "Ironing"
SERVICE_SPECIAL_GARMENTS = "Special Garments"

SERVICE_TYPES = {
    SERVICE_WASH_DRY_FOLD: 10.00,
    SERVICE_DRY_CLEANING: 15.00,
    SERVICE_IRONING: 5.00,
    SERVICE_SPECIAL_GARMENTS: 20.00,
}

# Payment Methods
PAYMENT_METHOD_CASH = "Cash"
PAYMENT_METHOD_CREDIT_CARD = "Credit Card"
PAYMENT_METHOD_DEBIT_CARD = "Debit Card"
PAYMENT_METHOD_ONLINE = "Online"

PAYMENT_METHODS = [
    PAYMENT_METHOD_CASH,
    PAYMENT_METHOD_CREDIT_CARD,
    PAYMENT_METHOD_DEBIT_CARD,
    PAYMENT_METHOD_ONLINE,
]

# Notification Types
NOTIFICATION_TYPE_SMS = "SMS"
NOTIFICATION_TYPE_EMAIL = "Email"
NOTIFICATION_TYPE_PUSH = "Push Notification"

NOTIFICATION_TYPES = [
    NOTIFICATION_TYPE_SMS,
    NOTIFICATION_TYPE_EMAIL,
    NOTIFICATION_TYPE_PUSH,
]
