name: Build Executables

on:
  push:
    branches: [ main, master, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Build Windows executable
        run: |
          pyinstaller app.spec

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: OrderManagementSystem-Windows
          path: dist/OrderManagementSystem

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Build Linux executable
        run: |
          pyinstaller app.spec

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: OrderManagementSystem-Linux
          path: dist/OrderManagementSystem

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Build macOS executable
        run: |
          pyinstaller app.spec

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: OrderManagementSystem-macOS
          path: dist/OrderManagementSystem

  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            OrderManagementSystem-Windows/**
            OrderManagementSystem-Linux/**
            OrderManagementSystem-macOS/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
